### ISSUE TITLE
No support for tables names different of model names

### ISSUE THREAD

**Issue by mtancoigne** [el-cms/superBake#28]
Currently, superBake creates models expecting the corresponding table exists. 

An option should be created in the config file to handle this, and the `sbc::populate()` method should take care of it.

``` yaml
defaults:
  model:
    ## Model name
    name: <modelName>
    ## Table name in DB
    tableName: <tableName>
    <other options>
```
