### ISSUE TITLE
Should we keep '<file>.targetFileName' in file configuration ?

### ISSUE THREAD

**Issue by mtancoigne** [el-cms/superBake#32]
After using superBake, I think this is useless, as complete target file name can be defined in `<file>.targetPath`

**Comment by mtancoigne** [comment]
I'll delete it.

**Comment by mtancoigne** [comment]
Removed `targetFileName` and `ext` from both `file` declarations and `menu` declarations in the configuration file.
You now have to specify all that in the `targetPath` option.
I.e:

``` YAML
---
appBase:
  files:
    flash_succcess:
      targetPath: View::Elements::flash_success.ctp
      template: elements::flash_message
      options:
        alertClass: success
  menus:
    public_menu:
      template: menu
      targetPath: elements::menus::public.ctp
```

These changes will be available in next commit.
