### ISSUE TITLE
Standardize comments in files

### ISSUE THREAD

**Issue by mtancoigne** [el-cms/superBake#36]
We need to setup comments standardization in files, to unify the presentation of the code.

Come here to discuss about it.

**For config file, I propose the following:**

``` YML
#--------------------------------------------------------------------------
#
# Very big section (general, defaults, plugins, theme)
#
#--------------------------------------------------------------------------
plugin:

  ## --------------------------------------------------------------------------
  ##  Someplugin: description
  ## ----------------------------
  ##  Contains: <controllers list>
  ## --------------------------------------------------------------------------
  ## Extended description,
  ## Extra help for special stuff...
  ## 
  ## Paragraphs separated by an empty line.
  ##
  Someplugin:

    ## --------------------------------------------------------------------------
    ##  Small section description
    ## ----------------------------
    parts:

      ##
      ##
      ## Sub  description
      ##
      ##
      SomePart:

        ##
        ## Sub-sub
        ##
        model:

          ##
          ## Sub-sub-sub section
          options:

            ## Simple line description (two # to know it's a comment for en entry) 
            someStuff: someValue
            ## Multiline
            ## comment.
            someStuff2: someValue

            ## Only one # for commented entries
#           commentedEntry: value  
            #anotherCommentedEntry: value   
```
