### ISSUE TITLE
Login action value resets with '*****'

### ISSUE THREAD

**Issue by mtancoigne** [el-cms/superBake#6]
Case: 
superBakeConfig

``` YAML
plugins:
  ## ...
  appBase:
    parts:
      Users:
        model:
          ## ...
        controller:
          actions:
            ## ... 
            admin:
              login:
                file: users::login
                hasView: true
## ...
```

gives me that :

``` PHP
array(
    'login' => '*****',
    'index' => array(
        'hasView' => true,
        'file' => '',
        'options' => array()
    ),
```

instead of

``` PHP
array(
    'login' => array(
        'hasView' => true,
        'file' => 'users::login',
        'options' => array()
    'index' => array(
        'hasView' => true,
        'file' => '',
        'options' => array()
    ),
```

If I change the action name to something else, that's OK... Weird.
